### ISSUE TITLE
Error on last codeblock of inference

### ISSUE THREAD

**Issue by dillfrescott** [anton-kashkin/hifi_vc#1]
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-13-e9758480f12e>](https://localhost:8080/#) in <module>
----> 1 traced = torch.jit.load(model_jit_path).eval()
      2 
      3 with torch.no_grad():
      4     converted = traced(wav_source, mel_ref, pitch)
      5 

[/usr/local/lib/python3.7/dist-packages/torch/jit/_serialization.py](https://localhost:8080/#) in load(f, map_location, _extra_files)
    160     cu = torch._C.CompilationUnit()
    161     if isinstance(f, str) or isinstance(f, pathlib.Path):
--> 162         cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
    163     else:
    164         cpp_module = torch._C.import_ir_module_from_buffer(

RuntimeError: PytorchStreamReader failed reading file data/886: invalid header or archive is corrupted
```

**Comment by dillfrescott** [comment]
This happened on 2 separate instances

**Comment by anton-kashkin** [comment]
Thanks for the feedback. Indeed, the model turned out to be non-working. I changed the download link, try it now

**Comment by dutchsing009** [comment]
@anton-kashkin Hello, is there any chance for you and your team to release the training code ?? or you still didn't get permission ? having the training code would be really awesome and very helpful.

**Comment by anton-kashkin** [comment]
@dutchsing009 unfortunately, we cannot release the training code now, because we are working on implementing the model in production (not in English) and do not want competing companies to use our code.

However, with a high probability, we will be able to publish the code in early 2023

**Comment by dutchsing009** [comment]
@anton-kashkin Really understandable , I wish all the best for you and your team and to succeed in what you will do next. (I also know that you will use it in Russian not English)  :)
