### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by qweteax1** [anton-kashkin/hifi_vc#2]
Error occurs in inference on google colab in this block {source_wav_path, target_wav_path = sample_audios(seen_dir)} even after putting the source and target path.

**Comment by dillfrescott** [comment]
I had this error too. You need both files in the seen directory. That worked for me.

**Comment by anton-kashkin** [comment]
Yes, `sample_audios` needs both audios to be in this directory. If your audio recordings are in different directories, you can assign paths manually.
